version: '3.9'

services:
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: order-service:latest
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}

      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}

      - SPRING_FLYWAY_URL=jdbc:postgresql://order-db:5432/${DB_NAME}
      - SPRING_FLYWAY_USER=${DB_USER}
      - SPRING_FLYWAY_PASSWORD=${DB_PASS}
    depends_on:
      - order-db
    networks:
      - soat-net
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  order-db:
    image: postgres:15-alpine
    container_name: order-db
    environment:
      - POSTGRES_DB=${DB_NAME:-order_db}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-mysecretpassword}
    ports:
      - "5433:5432"
    networks:
      - soat-net
    volumes:
      - order-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-order_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  soat-net:
    driver: bridge
    name: soat-net

volumes:
  order-db-data:
    name: order-db-data