apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - configmaps/order-service.yml
  - secrets/order-service.yml
  - deployments/order-service.yml
  - services/order-service.yml
  - hpa/order-service.yml